INSERT INTO `city` VALUES (1,'Alvaraes',1);
INSERT INTO `city` VALUES (2,'Anori',1);
INSERT INTO `city` VALUES (3,'Apui',1);
INSERT INTO `city` VALUES (4,'Autazes',1);
INSERT INTO `city` VALUES (5,'Barcelos',1);
INSERT INTO `city` VALUES (6,'Barreirinha',1);
INSERT INTO `city` VALUES (7,'Benjamin Constant',1);
INSERT INTO `city` VALUES (8,'Boca do Acre',1);
INSERT INTO `city` VALUES (9,'Borba',1);
INSERT INTO `city` VALUES (10,'Canutama',1);
INSERT INTO `city` VALUES (11,'Carauari',1);
INSERT INTO `city` VALUES (12,'Careiro',1);
INSERT INTO `city` VALUES (13,'Careiro da Varzea',1);
INSERT INTO `city` VALUES (14,'Coari',1);
INSERT INTO `city` VALUES (15,'Codajas',1);
INSERT INTO `city` VALUES (16,'Eirunepe',1);
INSERT INTO `city` VALUES (17,'Envira',1);
INSERT INTO `city` VALUES (18,'Fonte Boa',1);
INSERT INTO `city` VALUES (19,'Guajara',1);
INSERT INTO `city` VALUES (20,'Humaita',1);
INSERT INTO `city` VALUES (21,'Ipixuna',1);
INSERT INTO `city` VALUES (22,'Iranduba',1);
INSERT INTO `city` VALUES (23,'Itacoatiara',1);
INSERT INTO `city` VALUES (24,'Japura',1);
INSERT INTO `city` VALUES (25,'Jutai',1);
INSERT INTO `city` VALUES (26,'Labrea',1);
INSERT INTO `city` VALUES (27,'Manacapuru',1);
INSERT INTO `city` VALUES (28,'Manaquiri',1);
INSERT INTO `city` VALUES (29,'Manaus',1);
INSERT INTO `city` VALUES (30,'Manicore',1);
INSERT INTO `city` VALUES (31,'Maraa',1);
INSERT INTO `city` VALUES (32,'Maues',1);
INSERT INTO `city` VALUES (33,'Nhamunda',1);
INSERT INTO `city` VALUES (34,'Nova Olinda do Norte',1);
INSERT INTO `city` VALUES (35,'Novo Airao',1);
INSERT INTO `city` VALUES (36,'Novo Aripuana',1);
INSERT INTO `city` VALUES (37,'Parintins',1);
INSERT INTO `city` VALUES (38,'Pauini',1);
INSERT INTO `city` VALUES (39,'Rio Preto da Eva',1);
INSERT INTO `city` VALUES (40,'Santa Isabel do Rio Negro',1);
INSERT INTO `city` VALUES (41,'Santo Antonio do Ica',1);
INSERT INTO `city` VALUES (42,'Sao Gabriel da Cachoeira',1);
INSERT INTO `city` VALUES (43,'Sao Paulo de Olivenca',1);
INSERT INTO `city` VALUES (44,'Tabatinga',1);
INSERT INTO `city` VALUES (45,'Tapaua',1);
INSERT INTO `city` VALUES (46,'Tefe',1);
INSERT INTO `city` VALUES (47,'Tonantins',1);
INSERT INTO `city` VALUES (48,'Uarini',1);
INSERT INTO `city` VALUES (49,'Urucara',1);
INSERT INTO `city` VALUES (50,'Urucurituba',1);
INSERT INTO `city` VALUES (51,'Leticia',1);
INSERT INTO `city` VALUES (52,'Puerto Narino',1);
INSERT INTO `city` VALUES (53,'Achi',6);
INSERT INTO `city` VALUES (54,'Altos del Rosario',6);
INSERT INTO `city` VALUES (55,'Arenal',6);
INSERT INTO `city` VALUES (56,'Arjona',6);
INSERT INTO `city` VALUES (57,'Arroyohondo',6);
INSERT INTO `city` VALUES (58,'Barranco de Loba',6);
INSERT INTO `city` VALUES (59,'Calamar',6);
INSERT INTO `city` VALUES (60,'Cantagallo',6);
INSERT INTO `city` VALUES (61,'Cartagena',6);
INSERT INTO `city` VALUES (62,'Cicuco',6);
INSERT INTO `city` VALUES (63,'Clemencia',6);
INSERT INTO `city` VALUES (64,'Cordoba',6);
INSERT INTO `city` VALUES (65,'El Carmen de Bolivar',6);
INSERT INTO `city` VALUES (66,'El Guamo',6);
INSERT INTO `city` VALUES (67,'El Penon',6);
INSERT INTO `city` VALUES (68,'Hatillo de Loba',6);
INSERT INTO `city` VALUES (69,'Magangue',6);
INSERT INTO `city` VALUES (70,'Mahates',6);
INSERT INTO `city` VALUES (71,'Margarita',6);
INSERT INTO `city` VALUES (72,'Maria la Baja',6);
INSERT INTO `city` VALUES (73,'Mompos',6);
INSERT INTO `city` VALUES (74,'Montecristo',6);
INSERT INTO `city` VALUES (75,'Morales',6);
INSERT INTO `city` VALUES (76,'Pinillos',6);
INSERT INTO `city` VALUES (77,'Regidor',6);
INSERT INTO `city` VALUES (78,'Rio Viejo',6);
INSERT INTO `city` VALUES (79,'San Cristobal',6);
INSERT INTO `city` VALUES (80,'San Estanislao',6);
INSERT INTO `city` VALUES (81,'San Fernando',6);
INSERT INTO `city` VALUES (82,'San Jacinto',6);
INSERT INTO `city` VALUES (83,'San Jacinto del Cauca',6);
INSERT INTO `city` VALUES (84,'San Juan Nepomuceno',6);
INSERT INTO `city` VALUES (85,'San Martin de Loba',6);
INSERT INTO `city` VALUES (86,'San Pablo',6);
INSERT INTO `city` VALUES (87,'Santa Catalina',6);
INSERT INTO `city` VALUES (88,'Santa Rosa',6);
INSERT INTO `city` VALUES (89,'Santa Rosa del Sur',6);
INSERT INTO `city` VALUES (90,'Simiti',6);
INSERT INTO `city` VALUES (91,'Soplaviento',6);
INSERT INTO `city` VALUES (92,'Talaigua Nuevo',6);
INSERT INTO `city` VALUES (93,'Tiquisio',6);
INSERT INTO `city` VALUES (94,'Turbaco',6);
INSERT INTO `city` VALUES (95,'Turbana',6);
INSERT INTO `city` VALUES (96,'Villanueva',6);
INSERT INTO `city` VALUES (97,'Zambrano',6);
INSERT INTO `city` VALUES (98,'Buenavista',19);
INSERT INTO `city` VALUES (99,'Caimito',19);
INSERT INTO `city` VALUES (100,'Chalan',19);
INSERT INTO `city` VALUES (101,'Coloso',19);
INSERT INTO `city` VALUES (102,'Corozal',19);
INSERT INTO `city` VALUES (103,'El Roble',19);
INSERT INTO `city` VALUES (104,'Galeras',19);
INSERT INTO `city` VALUES (105,'Guaranda',19);
INSERT INTO `city` VALUES (106,'La Union',19);
INSERT INTO `city` VALUES (107,'Los Palmitos',19);
INSERT INTO `city` VALUES (108,'Majagual',19);
INSERT INTO `city` VALUES (109,'Morroa',19);
INSERT INTO `city` VALUES (110,'Ovejas',19);
INSERT INTO `city` VALUES (111,'Palmito',19);
INSERT INTO `city` VALUES (112,'Sampues',19);
INSERT INTO `city` VALUES (113,'San Benito Abad',19);
INSERT INTO `city` VALUES (114,'San Juan de Betulia',19);
INSERT INTO `city` VALUES (115,'San Marcos',19);
INSERT INTO `city` VALUES (116,'San Onofre',19);
INSERT INTO `city` VALUES (117,'San Pedro',19);
INSERT INTO `city` VALUES (118,'Since',19);
INSERT INTO `city` VALUES (119,'Sincelejo',19);
INSERT INTO `city` VALUES (120,'Sucre',19);
INSERT INTO `city` VALUES (121,'Tolu',19);
INSERT INTO `city` VALUES (122,'Toluviejo',19);
INSERT INTO `city` VALUES (123,'Guaranda',6);
INSERT INTO `city` VALUES (124,'San Miguel',6);
INSERT INTO `city` VALUES (125,'Bagua Grande',1);
INSERT INTO `city` VALUES (126,'Cajaruro',1);
INSERT INTO `city` VALUES (127,'Chachapoyas',1);
INSERT INTO `city` VALUES (128,'Jazan',1);
INSERT INTO `city` VALUES (129,'La Peca',1);
INSERT INTO `city` VALUES (130,'Puerto Ayacucho',1);
INSERT INTO `city` VALUES (131,'Anaco',2);
INSERT INTO `city` VALUES (132,'Barcelona',2);
INSERT INTO `city` VALUES (133,'Cantaura',2);
INSERT INTO `city` VALUES (134,'El Tigre',2);
INSERT INTO `city` VALUES (135,'Puerto la Cruz',2);
INSERT INTO `city` VALUES (136,'San Jose de Guanipa',2);
INSERT INTO `city` VALUES (137,'Guasdualito',3);
INSERT INTO `city` VALUES (138,'San Fernando',3);
INSERT INTO `city` VALUES (139,'Cagua',4);
INSERT INTO `city` VALUES (140,'El Limon',4);
INSERT INTO `city` VALUES (141,'La Victoria',4);
INSERT INTO `city` VALUES (142,'Las Teyerias',4);
INSERT INTO `city` VALUES (143,'Maracay',4);
INSERT INTO `city` VALUES (144,'Palo Negro',4);
INSERT INTO `city` VALUES (145,'San Mateo',4);
INSERT INTO `city` VALUES (146,'Turmero',4);
INSERT INTO `city` VALUES (147,'Villa de Cura',4);
INSERT INTO `city` VALUES (148,'Barinas',5);
INSERT INTO `city` VALUES (149,'Barinitas',5);
INSERT INTO `city` VALUES (150,'Ciudad Bolivar',6);
INSERT INTO `city` VALUES (151,'Ciudad Guayana',6);
INSERT INTO `city` VALUES (152,'Upata',6);
INSERT INTO `city` VALUES (153,'Goaigoaza',7);
INSERT INTO `city` VALUES (154,'Guacara',7);
INSERT INTO `city` VALUES (155,'Guigue',7);
INSERT INTO `city` VALUES (156,'Mariara',7);
INSERT INTO `city` VALUES (157,'Moron',7);
INSERT INTO `city` VALUES (158,'Puerto Cabello',7);
INSERT INTO `city` VALUES (159,'San Joaquin',7);
INSERT INTO `city` VALUES (160,'Tacarigua',7);
INSERT INTO `city` VALUES (161,'Valencia',7);
INSERT INTO `city` VALUES (162,'San Carlos',8);
INSERT INTO `city` VALUES (163,'Tinaquillo',8);
INSERT INTO `city` VALUES (164,'Coro',11);
INSERT INTO `city` VALUES (165,'Punta Cardon',11);
INSERT INTO `city` VALUES (166,'Punto Fijo',11);
INSERT INTO `city` VALUES (167,'Altagracia de Orituco',12);
INSERT INTO `city` VALUES (168,'Calabozo',12);
INSERT INTO `city` VALUES (169,'San Juan de los Morros',12);
INSERT INTO `city` VALUES (170,'Valle de la Pascua',12);
INSERT INTO `city` VALUES (171,'Zaraza',12);
INSERT INTO `city` VALUES (172,'Barquisimeto',13);
INSERT INTO `city` VALUES (173,'Cabudare',13);
INSERT INTO `city` VALUES (174,'Carora',13);
INSERT INTO `city` VALUES (175,'El Tocuyo',13);
INSERT INTO `city` VALUES (176,'Los Rastrojos',13);
INSERT INTO `city` VALUES (177,'Quibor',13);
INSERT INTO `city` VALUES (178,'Ejido',14);
INSERT INTO `city` VALUES (179,'El Vigia',14);
INSERT INTO `city` VALUES (180,'Merida',14);
INSERT INTO `city` VALUES (181,'Baruta',15);
INSERT INTO `city` VALUES (182,'Carrizal',15);
INSERT INTO `city` VALUES (183,'Catia La Mar',15);
INSERT INTO `city` VALUES (184,'Caucaguita',15);
INSERT INTO `city` VALUES (185,'Chacao',15);
INSERT INTO `city` VALUES (186,'Charallave',15);
INSERT INTO `city` VALUES (187,'Cua',15);
INSERT INTO `city` VALUES (188,'El Cafetal',15);
INSERT INTO `city` VALUES (189,'El Hatillo',15);
INSERT INTO `city` VALUES (190,'Filas de Mariche',15);
INSERT INTO `city` VALUES (191,'Guarenas',15);
INSERT INTO `city` VALUES (192,'Guatire',15);
INSERT INTO `city` VALUES (193,'La Dolorita',15);
INSERT INTO `city` VALUES (194,'Los Dos Caminos',15);
INSERT INTO `city` VALUES (195,'Los Teques',15);
INSERT INTO `city` VALUES (196,'Ocumare del Tuy',15);
INSERT INTO `city` VALUES (197,'Petare',15);
INSERT INTO `city` VALUES (198,'San Antonio de los Altos',15);
INSERT INTO `city` VALUES (199,'Santa Teresa',15);
INSERT INTO `city` VALUES (200,'Maturin',16);
INSERT INTO `city` VALUES (201,'Acarigua',18);
INSERT INTO `city` VALUES (202,'Araure',18);
INSERT INTO `city` VALUES (203,'Guanare',18);
INSERT INTO `city` VALUES (204,'Villa Bruzual',18);
INSERT INTO `city` VALUES (205,'Carupano',19);
INSERT INTO `city` VALUES (206,'Cumana',19);
INSERT INTO `city` VALUES (207,'La Fria',20);
INSERT INTO `city` VALUES (208,'Rubio',20);
INSERT INTO `city` VALUES (209,'San Antonio del Tachira',20);
INSERT INTO `city` VALUES (210,'San Cristobal',20);
INSERT INTO `city` VALUES (211,'San Juan de Colon',20);
INSERT INTO `city` VALUES (212,'Tariba',20);
INSERT INTO `city` VALUES (213,'Trujillo',21);
INSERT INTO `city` VALUES (214,'Valera',21);
INSERT INTO `city` VALUES (215,'Caraballeda',22);
INSERT INTO `city` VALUES (216,'La Guaira',22);
INSERT INTO `city` VALUES (217,'Maiquetia',22);
INSERT INTO `city` VALUES (218,'Chivacoa',23);
INSERT INTO `city` VALUES (219,'Nirgua',23);
INSERT INTO `city` VALUES (220,'San Felipe',23);
INSERT INTO `city` VALUES (221,'Yaritagua',23);
INSERT INTO `city` VALUES (222,'Bachaquero',24);
INSERT INTO `city` VALUES (223,'Cabimas',24);
INSERT INTO `city` VALUES (224,'Ciudad Ojeda',24);
INSERT INTO `city` VALUES (225,'Lagunillas',24);
INSERT INTO `city` VALUES (226,'Machiques',24);
INSERT INTO `city` VALUES (227,'Maracaibo',24);
INSERT INTO `city` VALUES (228,'San Carlos del Zulia',24);
INSERT INTO `city` VALUES (229,'Santa Rita',24);
INSERT INTO `city` VALUES (230,'Villa del Rosario',24);
