INSERT INTO `state` VALUES (1,'Amazonas');
INSERT INTO `state` VALUES (2,'Anzoategui');
INSERT INTO `state` VALUES (3,'Apure');
INSERT INTO `state` VALUES (4,'Aragua');
INSERT INTO `state` VALUES (5,'Barinas');
INSERT INTO `state` VALUES (6,'Bolivar');
INSERT INTO `state` VALUES (7,'Carabobo');
INSERT INTO `state` VALUES (8,'Cojedes');
INSERT INTO `state` VALUES (9,'Delta Amacuro');
INSERT INTO `state` VALUES (10,'Distrito Federal');
INSERT INTO `state` VALUES (11,'Falcon');
INSERT INTO `state` VALUES (12,'Guarico');
INSERT INTO `state` VALUES (13,'Lara');
INSERT INTO `state` VALUES (14,'Merida');
INSERT INTO `state` VALUES (15,'Miranda');
INSERT INTO `state` VALUES (16,'Monagas');
INSERT INTO `state` VALUES (17,'Nueva Esparta');
INSERT INTO `state` VALUES (18,'Portuguesa');
INSERT INTO `state` VALUES (19,'Sucre');
INSERT INTO `state` VALUES (20,'Tachira');
INSERT INTO `state` VALUES (21,'Trujillo');
INSERT INTO `state` VALUES (22,'Vargas');
INSERT INTO `state` VALUES (23,'Yaracuy');
INSERT INTO `state` VALUES (24,'Zulia');